---
jobs:
  release:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install @semantic-release/changelog -D
            - run: npm install @semantic-release/git -D
      - run: npx semantic-release
orbs:
  node: circleci/node@1.1.6
version: 2.1
workflows:
  production:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master
